name: Deploy site

on:
  push:
    branches: [main]
    paths:
      - "main/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build site
        run: make main-build

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SITE_SYNC_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SITE_SYNC_KEY_SECRET }}
          aws-region: ap-northeast-1

      - name: Sync to site S3 bucket
        run: |
          cd main/public
          aws s3 sync . s3://evertras.com
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build site
        run: make main-build-staging

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_SITE_SYNC_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SITE_SYNC_KEY_SECRET }}
          aws-region: ap-northeast-1

      - name: Sync to site S3 bucket
        run: |
          cd main/public
          aws s3 sync . s3://stg.evertras.com
